### ISSUE TITLE
Check solution

### ISSUE THREAD

**Issue by MatteoAndriolo** [MatteoAndriolo/OperationResearchLaboratory#29]
- [ ] Define list of values we need to provide
- [ ] Implement code

**Comment by MatteoAndriolo** [comment]
I think we should write at the end of the for loop that generates all the instances an OUTPUT_COMMENT which writes all the values we need and store them somewhere. 

We should also think about how to store all the results

**Comment by Reevoc** [comment]
Can we write on another file ?

**Comment by MatteoAndriolo** [comment]
Yes but we have to find a way to manage all the results
